services:
  - type: web
    name: recime-challenge-backend
    runtime: node
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: npm start
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/opt/render/.cache/puppeteer/chrome/linux-*/chrome-linux64/chrome"
